# Generated by Django 4.1.7 on 2023-07-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Persona'},
        ),
    ]
