# Generated by Django 4.2.2 on 2023-08-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_persona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
