# Generated by Django 4.2 on 2023-05-06 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad_total',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Cantidad Total'),
        ),
    ]
