# Generated by Django 4.2 on 2023-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_detalle_compra_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad_total',
            field=models.PositiveIntegerField(verbose_name='Cantidad Total'),
        ),
    ]
