# Generated by Django 4.2 on 2023-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_detalle_compra_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Total'),
        ),
    ]
