# Generated by Django 4.2 on 2023-05-09 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_detalle_compra_cantidad_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='cantidad_total',
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='La cantidad tiene que ser menor a 100', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Valor total'),
        ),
    ]
