# Generated by Django 4.2 on 2023-05-08 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
