# Generated by Django 4.2 on 2023-05-09 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='La cantidad tiene que ser menor a 100', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
