# Generated by Django 4.2 on 2023-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor total'),
        ),
    ]
