# Generated by Django 4.2 on 2023-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_detalle_venta_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad_total',
            field=models.PositiveIntegerField(verbose_name='Cantidad Total'),
        ),
    ]
