# Generated by Django 4.2 on 2023-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_detalle_venta_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor total'),
        ),
    ]
